backend:
  name: github
  repo: seanwlawrence/sushi-commerce
  branch: master
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images
display_url: https://sushi-commerce.netlify.com
collections:
  - name: settings
    label: Settings
    files:
      - name: storeDetails
        label: Store details
        file: /src/data/store-details.yml
        fields: 
          - name: title
            label: Title
            widget: string
            required: true
            default: Sushi Commerce
          - name: description
            label: Description
            widget: text
            required: true
            default: The best sushi on the planet.
          - name: keywords
            label: Keywords
            widget: list
            required: true
            default: 
              - sushi
              - sashimi
          - name: logo
            label: Logo
            widget: image
            required: true
            default: /static/images/logo.jpg
          - name: socialMedia
            label: Social media
            widget: list
            required: true
            default: 
            - site: instagram
              href: https://instagram.com/sushi-commerce
            fields:
              - name: site
                label: Site
                widget: select
                required: true
                options: 
                  - label: Instagram
                    value: instagram
                  - label: Facebook
                    value: facebook
                  - label: Twitter
                    value: twitter
                  - label: YouTube
                    value: youtube
              - name: href
                label: Url
                widget: string
                required: true
          - name: googleAnalytics
            label: Google Analytics snippet
            widget: text
            required: false
            default: UA-XXXXX-Y
          - name: customCSS
            label: Custom CSS
            widget: text
            required: false
            default: /* CSS goes here */
          - name: customJS
            label: Custom JavaScript
            widget: text
            required: false
            default: /* JavaScript goes here */
      # TODO: add theming support via Netlify CMS, so styling can be done without touching the index.scss file
      # - name: styles
      #   label: Styles
      #   file: src/data/styles.yml
      #   fields: 
      #     - name: colors
      #       label: Colors
      #       widget: object
      #       required: false
      #       fields: 
      #         - name: primary
      #           label: Primary
      #           widget: string
      #           required: false
      #         - name: info
      #           label: Info
      #           widget: string
      #           required: false
      #           default: 
      #         - name: link
      #           label: Link
      #           widget: string
      #           required: false
      #         - name: success
      #           label: Success
      #           widget: string
      #           required: false
      #         - name: warning
      #           label: Warning
      #           widget: string
      #           required: false
      #         - name: danger
      #           label: Danger
      #           widget: string
      #           required: false
      #     - name: fonts
      #       label: Fonts
      #       widget: object
      #       required: false
      #       fields: 
      #         - name: family
      #           label: Family
      #           widget: string
      #           required: false
      #         - name: sizes
      #           label: Sizes
      #           widget: object
      #           required: false
      #           fields: 
      #             - name: heading1
      #               label: Heading 1
      #               widget: string
      #               required: false
      #             - name: heading2
      #               label: Heading 2
      #               widget: string
      #               required: false
      #             - name: heading3
      #               label: Heading 3
      #               widget: string
      #               required: false
      #             - name: heading4
      #               label: Heading 4
      #               widget: string
      #               required: false
      #             - name: heading5
      #               label: Heading 5
      #               widget: string
      #               required: false
      #             - name: heading6
      #               label: Heading 6
      #               widget: string
      #               required: false
      #             - name: body
      #               label: Body
      #               widget: string
      #               required: false
      #         - name: weights
      #           label: Weights
      #           widget: object
      #           required: false
      #           fields:
      #             - name: headings
      #               label: Headings
      #               widget: string
      #               required: false
      #             - name: body
      #               label: Body
      #               widget: string
      #               required: false
      #     - name: buttonStyle
      #       label: Button style
      #       widget: select
      #       required: false
      #       default: squared
      #       options: 
      #         - label: Squared
      #           value: squared
      #         - label: Rounded
      #           value: rounded
      - name: navigation
        label: Navigation
        file: src/data/navigation.yml
        fields:
          - name: menuItems
            label: Menu items
            widget: list
            required: true
            default: 
              - page: Products
                to: /products
              - page: Posts
                to: /posts
              - page: Contact
                to: /contact
            fields: 
              - name: page
                label: Page
                widget: string
                required: true
              - name: to
                label: Url
                widget: string
                required: true
          - name: hideFooter
            label: Hide footer?
            widget: boolean
            required: false
            default: false
          - name: paypalCartButtonCode
            label: PayPal Cart button code
            widget: text
            required: false
            default: -----BEGIN PKCS7-----MIIG1QYJKoZIhvcNAQcEoIIGxjCCBsICAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYAzT6cMGz+P0apprtB21WNqEIcXvwk+csKyAe4vIpLx/CY0iHUJhJ8S3Lw4IHS2uIqnPhHgHWFdLu/V9Iue/lqeQIMdgOeeY7mrf7vkVrP13nnBSGFkiy2/Nft6N0SLbjedDAe7ddoaolondEXz6Loz3pUibG7q+3DPliJ2DAC5XDELMAkGBSsOAwIaBQAwUwYJKoZIhvcNAQcBMBQGCCqGSIb3DQMHBAg0H9PNiPyuSoAw5J0k0+MsGauCIE/SzJvsqboS1JX2wWxVCNSIsA8jyHviRz50Zm7MuYz1LSfC44JYoIIDhzCCA4MwggLsoAMCAQICAQAwDQYJKoZIhvcNAQEFBQAwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMB4XDTA0MDIxMzEwMTMxNVoXDTM1MDIxMzEwMTMxNVowgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBR07d/ETMS1ycjtkpkvjXZe9k+6CieLuLsPumsJ7QC1odNz3sJiCbs2wC0nLE0uLGaEtXynIgRqIddYCHx88pb5HTXv4SZeuv0Rqq4+axW9PLAAATU8w04qqjaSXgbGLP3NmohqM6bV9kZZwZLR/klDaQGo1u9uDb9lr4Yn+rBQIDAQABo4HuMIHrMB0GA1UdDgQWBBSWn3y7xm8XvVk/UtcKG+wQ1mSUazCBuwYDVR0jBIGzMIGwgBSWn3y7xm8XvVk/UtcKG+wQ1mSUa6GBlKSBkTCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb22CAQAwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQCBXzpWmoBa5e9fo6ujionW1hUhPkOBakTr3YCDjbYfvJEiv/2P+IobhOGJr85+XHhN0v4gUkEDI8r2/rNk1m0GA8HKddvTjyGw/XqXa+LSTlDYkqI8OwR8GEYj4efEtcRpRYBxV8KxAW93YDWzFGvruKnnLbDAF6VR5w/cCMn5hzGCAZowggGWAgEBMIGUMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbQIBADAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTgwNjAyMjA0MzQ2WjAjBgkqhkiG9w0BCQQxFgQUp32XEzlzDe+o2Mg/wpH4tF0XwJ8wDQYJKoZIhvcNAQEBBQAEgYBVzd030LMkmle/lK+wWcHtueR3z20SA4I/LXMj5YoJ3rAJzpFu1VBuP+zDpSQ7VEvGJ2YeQpyxewMwBj+Xp8Hyb2Yj3Fi11X1tzsZHuC2L37Om6ZMZ6EzMw5YIh2GGms79bXxOnrMChgbiLvqekN4bB3XBUO0CuRgJGnj/yePmMg==-----END PKCS7----
      - name: landingPage
        label: Landing page
        file: src/data/landing-page.yml
        fields:
          - name: banner
            label: Banner
            widget: object
            required: false
            fields:
              - name: heading
                label: Heading
                widget: string
                required: false
                default: The world's best sushi
              - name: subheading
                label: Subheading
                widget: string
                required: false
                default: Try it out yourself and see what everyone is talking about
              - name: backgroundImage
                label: Background image
                widget: image
                required: false
                default: /static/images/banner.jpg
              - name: overlayColor
                label: Overlay color
                widget: select
                required: false
                default: mojito
                options:
                  - label: Moon purple
                    value: moonPurple
                  - label: Shifter
                    value: shifter
                  - label: Quepal
                    value: quepal
                  - label: Pink flavour
                    value: pinkFlavour
                  - label: Orange fun
                    value: orangeFun
                  - label: Digital water
                    value: digitalWater
                  - label: Purpink
                    value: purpink
                  - label: Blue skies
                    value: blueSkies
                  - label: Nelson
                    value: nelson
                  - label: Aqualicious
                    value: aqualicious
                  - label: Kyoto
                    value: kyoto
                  - label: Mojito
                    value: mojito
                  - label: Lush
                    value: lush
              - name: button
                label: Button
                widget: object
                required: false
                fields:
                  - name: text
                    label: Text
                    widget: string
                    required: false
                    default: Order now 
                  - name: to
                    label: Url
                    widget: string
                    required: false
                    default: /products 
                  - name: color
                    label: Color
                    widget: select
                    required: false
                    default: primary
                    options: 
                      - label: Primary
                        value: primary
                      - label: Info
                        value: info
                      - label: Link
                        value: link
                      - label: White
                        value: white
          - name: about
            label: About
            widget: object
            required: false
            fields: 
              - name: heading
                label: Heading
                widget: string
                required: false
                default: About us 
              - name: text
                label: Text
                widget: text
                required: false
                default: We make sushi right. With the freshest ingredients around, world-remowned chefs and over 100 years of experience, we provide the best sushi experience that you can find anywhere. 
          - name: features
            label: Features
            widget: list
            required: false
            default: 
              - heading: Fresh
                text: Fresh seafood caught daily on our local pier
                icon: leaf
              - heading: Made with love
                text: Our world-class chefs love what they do
                icon: heart
              - heading: Award-winning
                text: Our kitchen has won over 100 awards
                icon: star
              - heading: Worldwide locations
                text: We have over 1000 locations worldwide
                icon: map 
            fields: 
              - name: heading
                label: Heading
                widget: string
                required: true
              - name: text
                label: Text
                widget: string
                required: true
              - name: icon
                label: Icon
                widget: select
                options:
                  - label: Calendar
                    value: calendar-check
                  - label: Chart
                    value: chart-bar
                  - label: Checkmark round
                    value: check-circle
                  - label: Checkmark square
                    value: check-square
                  - label: Clock
                    value: clock
                  - label: Copy
                    value: copy
                  - label: Comment
                    value: comment-dots
                  - label: Compass
                    value: compass
                  - label: Credit card
                    value: credit-card
                  - label: Edit
                    value: edit
                  - label: Eye
                    value: eye
                  - label: File
                    value: file
                  - label: Folder
                    value: folder-open
                  - label: Gem
                    value: gem
                  - label: Handshake
                    value: handshake
                  - label: Heart
                    value: heart
                  - label: ID
                    value: id-card
                  - label: Images
                    value: images
                  - label: Keyboard
                    value: keyboard
                  - label: Leaf
                    value: leaf
                  - label: Lightbulb
                    value: lightbulb
                  - label: Map
                    value: map
                  - label: Money
                    value: money-bill-alt
                  - label: Paper airplane
                    value: paper-plane
                  - label: Add
                    value: plus-square
                  - label: Save
                    value: save
                  - label: Share
                    value: share-square
                  - label: Star
                    value: star
                  - label: Sticky note
                    value: sticky-note
                  - label: Thumbs up
                    value: thumbs-up
                  - label: User
                    value: user
          - name: testimonials
            label: Testimonials
            widget: list
            required: false
            default: 
            - name: Satoshi Nakamoto - Famous Chef
              text: The best sushi that I have ever tasted.
            - name: Tim Wheeler - Best-selling Author
              text: I eat here every day... and I can't stop raving about how fresh this sushi is.
            - name: Alejandra Gomez - Food Crtic
              text: Can it get any better than Sushi Commerce? Seriously... I don't think it can.
            fields:
              - name: name
                label: name
                widget: string
                required: true
              - name: text
                label: Text
                widget: text
                required: true

  - name: products
    label: Products
    folder: src/pages/products
    create: true
    fields: 
      - name: template
        widget: hidden
        default: product
      - name: title
        label: Title
        widget: string
        required: true
      - name: price
        label: Price
        widget: number
        required: true
      - name: featuredImage
        label: Image
        widget: object
        required: true
        fields: 
          - name: src
            label: Select image...
            widget: image
            required: true
          - name: alt
            label: Description
            widget: string
            required: false
            default: Product image
      - name: features
        label: Features (separate with comma)
        widget: text
        required: true
      - name: paypalAddToCartButtonCode
        label: PayPal Add to Cart Button code
        widget: text
        required: false
      - name: paypalBuyNowButtonCode
        label: PayPal Buy Now Button code
        widget: text
        required: false
      - name: coinbaseCommerceButtonLink
        label: Coinbase Commerce Button link
        widget: text
        required: false
      - name: tags
        label: Tags
        widget: list
        required: false
      - name: body
        label: Description
        widget: markdown
        required: false
  - name: posts
    label: Posts
    folder: src/pages/posts
    create: true
    fields: 
      - name: template
        widget: hidden
        default: post
      - name: title
        label: Title
        widget: string
        required: true
      - name: date
        label: Date
        widget: date
        required: true
      - name: body
        label: Body
        widget: markdown
        required: true
      - name: featuredImage
        label: Featured image
        widget: object
        required: false
        fields: 
          - name: src
            label: Select image...
            widget: image
            required: true
          - name: alt
            label: Description
            widget: string
            required: false
            default: Featured image
      - name: tags
        label: Tags
        widget: list
        required: false
  - name: pages
    label: Pages
    folder: src/pages/
    create: true
    fields: 
      - name: template
        widget: hidden
        default: page
      - name: title
        label: Title
        widget: string
        required: true
      - name: body
        label: Body
        widget: markdown
        required: true
      - name: tags
        label: Tags
        widget: list
        required: false

      
        




              

              
